/* Browser-only batch analytics. Counts and rates are computed from imported records,
   never generated by an LLM. CSV/JSON schema: docs/analysis_cases.template.csv. */
let importedCases = [];
let importedFileName = '';
let lastDashboardData = null;

const riskMap = { high: 'high', '高': 'high', '高風險': 'high', medium: 'medium', med: 'medium', '中': 'medium', '中風險': 'medium', low: 'low', '低': 'low', '低風險': 'low' };
const outcomeMap = { upheld: 'upheld', '成立': 'upheld', partial: 'partial', '部分成立': 'partial', rejected: 'rejected', '不成立': 'rejected', pending: 'pending', '處理中': 'pending', '審查中': 'pending' };
const outcomeLabel = { upheld: '成立', partial: '部分成立', rejected: '不成立', pending: '處理中' };

const list = value => Array.isArray(value) ? value.map(String).filter(Boolean) : String(value || '').split(/[|；;、]/).map(v => v.trim()).filter(Boolean);
const amount = value => { const n = Number(String(value ?? '').replace(/[^0-9.-]/g, '')); return Number.isFinite(n) && n >= 0 ? n : null; };
const value = id => document.getElementById(id)?.value || 'all';

function normalise(raw, index) {
  const receivedAt = String(raw.receivedAt || raw.received_at || '').trim();
  const riskLevel = riskMap[String(raw.riskLevel || raw.risk_level || '').trim().toLowerCase()];
  const outcome = outcomeMap[String(raw.outcome || '').trim().toLowerCase()];
  const disputedAmount = amount(raw.disputedAmount || raw.disputed_amount);
  const exposureCount = Number(raw.exposureCount || raw.exposure_count);
  const caseId = String(raw.caseId || raw.case_id || '').trim();
  if (!caseId || Number.isNaN(new Date(receivedAt).getTime()) || !riskLevel || !outcome || disputedAmount === null || !Number.isFinite(exposureCount) || exposureCount <= 0) throw new Error(`第 ${index + 1} 筆缺少必要欄位或格式錯誤。`);
  return { caseId, receivedAt: receivedAt.slice(0, 10), category: String(raw.category || '').trim() || '未分類', product: String(raw.product || '').trim() || '未分類', segment: String(raw.segment || '').trim() || '未分類', channel: String(raw.channel || '').trim() || '未提供', productVersion: String(raw.productVersion || raw.product_version || '').trim() || '未提供', riskLevel, outcome, disputedAmount, exposureCount, regulations: list(raw.regulations || raw.regulation), violations: list(raw.violations || raw.violationTypes || raw.violation_types), evidence: list(raw.evidence || raw.evidenceRefs || raw.evidence_refs) };
}

function parseCsv(text) {
  const rows = []; let row = [], field = '', quoted = false;
  for (let i = 0; i < text.length; i += 1) { const c = text[i]; if (quoted && c === '"' && text[i + 1] === '"') { field += c; i += 1; } else if (c === '"') quoted = !quoted; else if (c === ',' && !quoted) { row.push(field); field = ''; } else if ((c === '\n' || c === '\r') && !quoted) { if (c === '\r' && text[i + 1] === '\n') i += 1; row.push(field); field = ''; if (row.some(v => v.trim())) rows.push(row); row = []; } else field += c; }
  row.push(field); if (row.some(v => v.trim())) rows.push(row);
  if (rows.length < 2) throw new Error('CSV 至少需要標題列及一筆資料。');
  const headers = rows.shift().map(v => v.replace(/^\uFEFF/, '').trim());
  return rows.map(values => Object.fromEntries(headers.map((header, i) => [header, values[i] || ''])));
}

function status(message, error = false) { const el = document.getElementById('analysis-data-status'); if (el) { el.textContent = message; el.style.color = error ? '#b91c1c' : '#475569'; } }

async function importAnalyticsFile(event) {
  const file = event.target.files?.[0]; if (!file) return;
  try { const text = await file.text(); const parsed = file.name.toLowerCase().endsWith('.json') ? JSON.parse(text) : parseCsv(text); const records = Array.isArray(parsed) ? parsed : parsed.cases; if (!Array.isArray(records)) throw new Error('JSON 必須是案件陣列或含有 cases 陣列。'); importedCases = records.map(normalise); importedFileName = file.name; loadBatchAnalysis(); }
  catch (error) { importedCases = []; importedFileName = ''; clearDashboard(`匯入失敗：${error.message}`); status(`匯入失敗：${error.message}`, true); }
  finally { event.target.value = ''; }
}

function downloadAnalyticsTemplate() {
  const content = 'caseId,receivedAt,category,product,segment,channel,productVersion,riskLevel,outcome,disputedAmount,exposureCount,regulations,violations,evidence\nC-DEMO-001,2026-07-01,investment,policy,senior,branch,P2026.1,high,upheld,150000,12000,金融消費者保護法第9條|金融消費者保護法第10條,適合度評估不足|風險揭露不足,錄音檔#A01|KYC#K12\n';
  const url = URL.createObjectURL(new Blob([content], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'analysis_cases.template.csv'; a.click(); URL.revokeObjectURL(url);
}

function selectedCases() {
  const category = value('filter-category'), product = value('filter-product'), segment = value('filter-segment');
  return importedCases.filter(r => (category === 'all' || r.category === category) && (product === 'all' || r.product === product) && (segment === 'all' || r.segment === segment)).sort((a, b) => new Date(b.receivedAt) - new Date(a.receivedAt)).slice(0, Number(value('filter-volume')));
}
function outcomeWeight(record) { return record.outcome === 'upheld' ? 1 : record.outcome === 'partial' ? .5 : 0; }

function calculate(records) {
  const totalExposure = records.reduce((sum, r) => sum + r.exposureCount, 0), upheld = records.reduce((sum, r) => sum + outcomeWeight(r), 0), rate = totalExposure ? upheld / totalExposure * 10000 : 0;
  const matrix = new Map(), graphs = new Map(), violations = new Map(), products = new Map();
  records.forEach(r => {
    const stat = products.get(r.product) || { exposure: 0, upheld: 0, amount: 0 }; stat.exposure += r.exposureCount; stat.upheld += outcomeWeight(r); stat.amount += r.disputedAmount; products.set(r.product, stat);
    r.violations.forEach(v => violations.set(v, (violations.get(v) || 0) + 1));
    (r.regulations.length ? r.regulations : ['未標註法規']).forEach(law => {
      const key = `${r.product}\u0000${law}`, item = matrix.get(key) || { product: r.product, law, highRisk: 0, medRisk: 0, lowRisk: 0 }; if (r.riskLevel === 'high') item.highRisk += 1; else if (r.riskLevel === 'medium') item.medRisk += 1; else item.lowRisk += 1; matrix.set(key, item);
      const graph = graphs.get(law) || { law, obligations: [], consequences: [], cases: [], evidence: [] }; r.violations.forEach(v => !graph.obligations.includes(v) && graph.obligations.push(v)); !graph.consequences.includes(outcomeLabel[r.outcome]) && graph.consequences.push(outcomeLabel[r.outcome]); graph.cases.push({ id: r.caseId }); r.evidence.forEach(e => !graph.evidence.includes(e) && graph.evidence.push(e)); graphs.set(law, graph);
    });
  });
  const product = [...products.entries()].map(([name, stat]) => ({ name, rate: stat.exposure ? stat.upheld / stat.exposure : 0, amount: stat.amount })).sort((a, b) => b.rate - a.rate || b.amount - a.amount)[0];
  const topViolations = [...violations.entries()].sort((a, b) => b[1] - a[1]).slice(0, 4).map(([name, count]) => `${name}（${count}）`);
  const period = records.length ? `${records.at(-1).receivedAt} 至 ${records[0].receivedAt}` : '無資料';
  return { records, period, matrix: [...matrix.values()].sort((a, b) => b.highRisk - a.highRisk || b.medRisk - a.medRisk), lawGraph: [...graphs.values()].map(g => ({ ...g, cases: g.cases.slice(0, 3) })), riskData: { violations: topViolations }, narrative: records.length ? `分析 ${records.length} 筆案件（${period}）。依匯入之 exposureCount 作分母，成立等值風險率為每萬曝險 ${rate.toFixed(2)} 件；最高風險商品為 ${product?.name || '未分類'}。主要控制缺口：${topViolations.join('、') || '未標註'}。此結論僅來自可回溯案件與 evidence 欄位，不含模型估算的罰鍰、節省或因果宣稱。` : '篩選後無案件。', metrics: { avgLaw: records.length ? (records.reduce((sum, r) => sum + r.regulations.length, 0) / records.length).toFixed(1) : '—', highRiskProduct: product?.name || '—', rate: records.length ? `${rate.toFixed(2)} / 萬` : '—', traced: `${records.filter(r => r.evidence.length).length} / ${records.length}` } };
}

function loadBatchAnalysis() {
  if (!importedCases.length) { clearDashboard('尚未載入案件資料。此儀表板不使用模擬數據或 LLM 猜測。'); status('尚未載入案件資料：請先匯入 CSV／JSON。', true); return; }
  lastDashboardData = calculate(selectedCases()); renderDashboard(lastDashboardData); status(`資料來源：${importedFileName}；分析 ${lastDashboardData.records.length} 筆；期間 ${lastDashboardData.period}。`);
}
function applyQuickFilter(preset) { if (preset === 'case_invest') { document.getElementById('filter-category').value = 'investment'; document.getElementById('filter-product').value = 'policy'; document.getElementById('filter-segment').value = 'senior'; } else { document.getElementById('filter-category').value = 'insurance'; document.getElementById('filter-product').value = 'all'; document.getElementById('filter-segment').value = 'all'; } loadBatchAnalysis(); }

function clearDashboard(message) { document.getElementById('narrative-insight-text').textContent = message; const body = document.getElementById('matrix-tbody'); body.replaceChildren(); const tr = document.createElement('tr'), td = document.createElement('td'); td.colSpan = 4; td.textContent = message; td.style.padding = '12px'; tr.appendChild(td); body.appendChild(tr); const graph = document.getElementById('knowledge-graph'); graph.replaceChildren(); graph.textContent = message; ['metric-avg-law', 'metric-high-risk-product', 'metric-saved-amount', 'metric-traced-cases'].forEach(id => { const el = document.getElementById(id); if (el) el.textContent = '—'; }); }
function renderDashboard(data) { document.getElementById('narrative-insight-text').textContent = data.narrative; renderMatrix(data); renderGraph(data); document.getElementById('metric-avg-law').textContent = data.metrics.avgLaw; document.getElementById('metric-high-risk-product').textContent = data.metrics.highRiskProduct; document.getElementById('metric-saved-amount').textContent = data.metrics.rate; document.getElementById('metric-traced-cases').textContent = data.metrics.traced; }
function renderMatrix(data) { const body = document.getElementById('matrix-tbody'); body.replaceChildren(); data.matrix.forEach(item => { const tr = document.createElement('tr'), head = document.createElement('td'); head.style.cssText = 'padding:8px 6px;border-bottom:1px solid #f1f5f9;text-align:left;'; const p = document.createElement('div'); p.textContent = item.product; const l = document.createElement('span'); l.style.cssText = 'font-size:.7rem;color:#94a3b8'; l.textContent = `涉：${item.law}`; head.append(p, l); tr.appendChild(head); [item.highRisk, item.medRisk, item.lowRisk].forEach(n => { const td = document.createElement('td'); td.style.padding = '8px 6px'; td.textContent = `${n} 件`; tr.appendChild(td); }); body.appendChild(tr); }); if (!data.matrix.length) { const tr = document.createElement('tr'), td = document.createElement('td'); td.colSpan = 4; td.textContent = '篩選後無可計算的法規風險資料。'; td.style.padding = '12px'; tr.appendChild(td); body.appendChild(tr); } }
function renderGraph(data) { const container = document.getElementById('knowledge-graph'); container.replaceChildren(); if (!data.lawGraph.length) { container.textContent = '篩選後無法規關聯資料。'; return; } const listEl = document.createElement('div'); listEl.style.cssText = 'padding:12px;display:grid;gap:8px;font-size:.78rem;'; data.lawGraph.slice(0, 8).forEach(item => { const card = document.createElement('div'); card.className = 'net-node node-law'; card.style.cssText = 'position:static;width:auto;white-space:normal;'; const title = document.createElement('strong'); title.textContent = `⚖️ ${item.law}`; const detail = document.createElement('div'); detail.textContent = `控制缺口：${item.obligations.slice(0, 3).join('、') || '未標註'}｜結果：${item.consequences.join('、')}｜案件：${item.cases.map(c => c.id).join('、')}`; const evidence = document.createElement('div'); evidence.style.color = '#475569'; evidence.textContent = `證據索引：${item.evidence.slice(0, 3).join('、') || '未提供'}`; card.append(title, detail, evidence); listEl.appendChild(card); }); container.appendChild(listEl); }
function triggerExport() { if (!lastDashboardData) { alert('請先載入並分析案件資料。'); return; } const d = lastDashboardData, rows = d.matrix.map(r => `| ${r.product} / ${r.law} | ${r.highRisk} | ${r.medRisk} | ${r.lowRisk} |`).join('\n'); const text = `# 合規風險批次分析報告\n\n資料來源：${importedFileName}\n分析期間：${d.period}\n\n## 敘事洞察\n${d.narrative}\n\n## 指標\n- 平均引用法規數：${d.metrics.avgLaw}\n- 最高風險商品：${d.metrics.highRiskProduct}\n- 成立等值風險率：${d.metrics.rate}\n- 有證據索引案件：${d.metrics.traced}\n\n## 矩陣\n| 商品 / 法規 | 高 | 中 | 低 |\n|---|---:|---:|---:|\n${rows}\n\n> 所有數字依匯入資料計算，未含模型估算的罰鍰、節省或因果結論。\n`; const url = URL.createObjectURL(new Blob([text], { type: 'text/markdown;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = `Batch_Analysis_Report_${Date.now()}.md`; a.click(); URL.revokeObjectURL(url); }
window.addEventListener('DOMContentLoaded', () => clearDashboard('尚未載入案件資料。請匯入案件 CSV／JSON 後開始分析。'));
